# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYgJYNDZRueAZorIKi2THZ_Qou0RHAtR
"""

print(dir(str))

a='hello world'
b=a.upper()
print(b)

a='HELLO WORLD'
b=a.lower()
print(b)

a='hElLO wORlD'
b=a.swapcase()
print(b)

a='hello world'
b=a.title()
print(b)

a='HELLO world'
b=a.replace('world','sai priya')
print(b)

a='1234ka'
b=a.isdigit()
print(b)

a=range(10)
print(a)

a=range(10)
b=list(a)
print(b)

#start,stop then steps
my_list=list(range(5,15,2))
print(my_list)

def calculate_sum(*args):
  total=sum(args)
  return total
print("sum of 1,2,3:",calculate_sum(1,2,3))
print("sum of 1,2,3,4:",calculate_sum(1,2,3,4))

def add_numbers (a,b):
  result=a+b
  return result
result2=add_numbers(10,2)
print(result2)

#creating a program and adding two or more features to it
#predefined correct username and password
correct_username='admin'
correct_password='1234'
while True:
  #prompt the user to get input
  username=input("Enter your username:")
  password=input("Enter your password:")
  if username==correct_username and password==correct_password:
    print("Login Successfull")
    break
  else:
    print("Invalid username and password.please try again.")

#creating a program and adding two or more features to it
#predefined correct username and password
correct_username='admin'
correct_password='1234'
while True:
  #prompt the user to get input
  username=input("Enter your username:")
  password=input("Enter your password:")
  if username==correct_username and password==correct_password:
    print("Login Successfull")
    break
  else:
    print("Invalid username and password.please try again.")

# user defined assignment
def square(num):
    return num * num
print(square(4))

#Built-in assignment
string = "Hello, World!"
length = len(string)
print("Length of the text:", length)

#Built-in assignment
numbers=[20,40,30]
maximum=max(numbers)
print("Maximum of numbers:",maximum)