# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cL--wDf8s-mjKX_XUTpJDJ3fHMYu4wHa
"""

def sum_of_evens(n):
    if n < 1:
        return "Please enter a positive integer."
    total = sum(number for number in range(1, n + 1) if number % 2 == 0)
    return total
try:
    n = int(input("Enter a positive integer: "))
    result = sum_of_evens(n)
    print(f"The sum of all even numbers between 1 and {n} is: {result}")
except ValueError:
    print("Invalid input! Please enter a positive integer.")
