# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JRxYRsVukvr46XN7rDhcZHC6uS5O4HP3
"""

list=[1,1.5]

t=[1,2,3,4,5]
t[1:3]

t[:4]

t[3:]